version: '3.8'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dating-app-fe
    ports:
      - '5173:80'
    networks:
      - dating-app-network

networks:
  dating-app-network:
    driver: bridge
    external: true
